// Generated by `pnpm supabase:types`. Do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.5';
  };
  public: {
    Tables: {
      admin_profiles: {
        Row: {
          created_at: string;
          id: string;
          is_active: boolean;
          role: Database['public']['Enums']['admin_role'];
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          is_active?: boolean;
          role?: Database['public']['Enums']['admin_role'];
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          is_active?: boolean;
          role?: Database['public']['Enums']['admin_role'];
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      audit_logs: {
        Row: {
          action: string;
          admin_user_id: string | null;
          created_at: string;
          entity_id: string | null;
          entity_type: string;
          id: string;
          metadata: Json;
        };
        Insert: {
          action: string;
          admin_user_id?: string | null;
          created_at?: string;
          entity_id?: string | null;
          entity_type: string;
          id?: string;
          metadata?: Json;
        };
        Update: {
          action?: string;
          admin_user_id?: string | null;
          created_at?: string;
          entity_id?: string | null;
          entity_type?: string;
          id?: string;
          metadata?: Json;
        };
        Relationships: [];
      };
      events: {
        Row: {
          address: string;
          ceremony_time: string | null;
          contact_phone: string | null;
          created_at: string;
          description: string | null;
          event_date: string;
          event_type: Database['public']['Enums']['event_type'];
          google_maps_url: string | null;
          honoree_display_name: string;
          hosts_names: string;
          id: string;
          is_active: boolean;
          reception_time: string | null;
          side_a_label: string | null;
          side_b_label: string | null;
          title: string;
          updated_at: string;
          venue_name: string;
          waze_url: string | null;
        };
        Insert: {
          address: string;
          ceremony_time?: string | null;
          contact_phone?: string | null;
          created_at?: string;
          description?: string | null;
          event_date: string;
          event_type?: Database['public']['Enums']['event_type'];
          google_maps_url?: string | null;
          honoree_display_name: string;
          hosts_names: string;
          id?: string;
          is_active?: boolean;
          reception_time?: string | null;
          side_a_label?: string | null;
          side_b_label?: string | null;
          title: string;
          updated_at?: string;
          venue_name: string;
          waze_url?: string | null;
        };
        Update: {
          address?: string;
          ceremony_time?: string | null;
          contact_phone?: string | null;
          created_at?: string;
          description?: string | null;
          event_date?: string;
          event_type?: Database['public']['Enums']['event_type'];
          google_maps_url?: string | null;
          honoree_display_name?: string;
          hosts_names?: string;
          id?: string;
          is_active?: boolean;
          reception_time?: string | null;
          side_a_label?: string | null;
          side_b_label?: string | null;
          title?: string;
          updated_at?: string;
          venue_name?: string;
          waze_url?: string | null;
        };
        Relationships: [];
      };
      guests: {
        Row: {
          created_at: string;
          event_id: string;
          family_side: Database['public']['Enums']['family_side'] | null;
          full_name: string;
          id: string;
          invite_token_hash: string | null;
          is_active: boolean;
          phone: string;
          phone_normalized: string;
          token_expires_at: string | null;
          token_revoked_at: string | null;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          event_id: string;
          family_side?: Database['public']['Enums']['family_side'] | null;
          full_name: string;
          id?: string;
          invite_token_hash?: string | null;
          is_active?: boolean;
          phone: string;
          phone_normalized: string;
          token_expires_at?: string | null;
          token_revoked_at?: string | null;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          event_id?: string;
          family_side?: Database['public']['Enums']['family_side'] | null;
          full_name?: string;
          id?: string;
          invite_token_hash?: string | null;
          is_active?: boolean;
          phone?: string;
          phone_normalized?: string;
          token_expires_at?: string | null;
          token_revoked_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'guests_event_id_fkey';
            columns: ['event_id'];
            isOneToOne: false;
            referencedRelation: 'events';
            referencedColumns: ['id'];
          },
        ];
      };
      idempotency_keys: {
        Row: {
          created_at: string;
          event_id: string;
          expires_at: string;
          id: string;
          idempotency_key_hash: string;
          request_fingerprint: string;
          response_payload: Json;
          response_status: number;
          rsvp_id: string | null;
        };
        Insert: {
          created_at?: string;
          event_id: string;
          expires_at: string;
          id?: string;
          idempotency_key_hash: string;
          request_fingerprint: string;
          response_payload: Json;
          response_status: number;
          rsvp_id?: string | null;
        };
        Update: {
          created_at?: string;
          event_id?: string;
          expires_at?: string;
          id?: string;
          idempotency_key_hash?: string;
          request_fingerprint?: string;
          response_payload?: Json;
          response_status?: number;
          rsvp_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'idempotency_keys_event_id_fkey';
            columns: ['event_id'];
            isOneToOne: false;
            referencedRelation: 'events';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'idempotency_keys_rsvp_id_fkey';
            columns: ['rsvp_id'];
            isOneToOne: false;
            referencedRelation: 'rsvps';
            referencedColumns: ['id'];
          },
        ];
      };
      invite_sessions: {
        Row: {
          created_at: string;
          event_id: string;
          expires_at: string;
          guest_id: string;
          id: string;
          revoked_at: string | null;
          session_token_hash: string;
        };
        Insert: {
          created_at?: string;
          event_id: string;
          expires_at: string;
          guest_id: string;
          id?: string;
          revoked_at?: string | null;
          session_token_hash: string;
        };
        Update: {
          created_at?: string;
          event_id?: string;
          expires_at?: string;
          guest_id?: string;
          id?: string;
          revoked_at?: string | null;
          session_token_hash?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'invite_sessions_event_id_fkey';
            columns: ['event_id'];
            isOneToOne: false;
            referencedRelation: 'events';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'invite_sessions_guest_id_fkey';
            columns: ['guest_id'];
            isOneToOne: false;
            referencedRelation: 'guests';
            referencedColumns: ['id'];
          },
        ];
      };
      rsvps: {
        Row: {
          adults_count: number;
          attendance_status: Database['public']['Enums']['attendance_status'];
          babies_count: number;
          children_count: number;
          consent: boolean;
          dietary_requirements: string | null;
          event_id: string;
          family_side: Database['public']['Enums']['family_side'] | null;
          full_name: string;
          guest_id: string | null;
          id: string;
          notes: string | null;
          phone: string;
          phone_normalized: string;
          source: Database['public']['Enums']['rsvp_source'];
          submitted_at: string;
          update_token_expires_at: string | null;
          update_token_hash: string | null;
          updated_at: string;
        };
        Insert: {
          adults_count?: number;
          attendance_status: Database['public']['Enums']['attendance_status'];
          babies_count?: number;
          children_count?: number;
          consent: boolean;
          dietary_requirements?: string | null;
          event_id: string;
          family_side?: Database['public']['Enums']['family_side'] | null;
          full_name: string;
          guest_id?: string | null;
          id?: string;
          notes?: string | null;
          phone: string;
          phone_normalized: string;
          source: Database['public']['Enums']['rsvp_source'];
          submitted_at?: string;
          update_token_expires_at?: string | null;
          update_token_hash?: string | null;
          updated_at?: string;
        };
        Update: {
          adults_count?: number;
          attendance_status?: Database['public']['Enums']['attendance_status'];
          babies_count?: number;
          children_count?: number;
          consent?: boolean;
          dietary_requirements?: string | null;
          event_id?: string;
          family_side?: Database['public']['Enums']['family_side'] | null;
          full_name?: string;
          guest_id?: string | null;
          id?: string;
          notes?: string | null;
          phone?: string;
          phone_normalized?: string;
          source?: Database['public']['Enums']['rsvp_source'];
          submitted_at?: string;
          update_token_expires_at?: string | null;
          update_token_hash?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'rsvps_event_id_fkey';
            columns: ['event_id'];
            isOneToOne: false;
            referencedRelation: 'events';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'rsvps_guest_id_fkey';
            columns: ['guest_id'];
            isOneToOne: false;
            referencedRelation: 'guests';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_public_event: {
        Args: never;
        Returns: Database['public']['CompositeTypes']['public_event'];
        SetofOptions: {
          from: '*';
          to: 'public_event';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      is_admin: { Args: never; Returns: boolean };
      is_owner: { Args: never; Returns: boolean };
    };
    Enums: {
      admin_role: 'admin' | 'owner';
      attendance_status: 'attending' | 'not_attending' | 'maybe';
      event_type:
        | 'brit_mila'
        | 'britah'
        | 'pidyon_haben'
        | 'upsherin'
        | 'bar_mitzvah'
        | 'bat_mitzvah'
        | 'engagement'
        | 'henna'
        | 'wedding'
        | 'birthday'
        | 'other';
      family_side: 'side_a' | 'side_b' | 'other';
      rsvp_source: 'personal_link' | 'public_form';
    };
    CompositeTypes: {
      public_event: {
        id: string | null;
        event_type: Database['public']['Enums']['event_type'] | null;
        title: string | null;
        hosts_names: string | null;
        honoree_display_name: string | null;
        event_date: string | null;
        ceremony_time: string | null;
        reception_time: string | null;
        venue_name: string | null;
        address: string | null;
        waze_url: string | null;
        google_maps_url: string | null;
        contact_phone: string | null;
        description: string | null;
        side_a_label: string | null;
        side_b_label: string | null;
      };
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] &
        DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      admin_role: ['admin', 'owner'],
      attendance_status: ['attending', 'not_attending', 'maybe'],
      event_type: [
        'brit_mila',
        'britah',
        'pidyon_haben',
        'upsherin',
        'bar_mitzvah',
        'bat_mitzvah',
        'engagement',
        'henna',
        'wedding',
        'birthday',
        'other',
      ],
      family_side: ['side_a', 'side_b', 'other'],
      rsvp_source: ['personal_link', 'public_form'],
    },
  },
} as const;
