import type { Locale } from '@/lib/i18n';

/**
 * Product copy for the authenticated and invitation surfaces.
 *
 * Marketing/auth/legal copy already lives in config/dictionary. This module covers the
 * parts of the product that were historically Hebrew-only: invitations, RSVP, the host
 * dashboard, guest management and premium tools. Keeping both locales beside each other
 * makes missing keys a compile-time problem instead of a production language leak.
 */
const APP_COPY = {
  he: {
    publicEvent: {
      brandedInvitation: 'הזמנה ממותגת',
      personalBrandedInvitation: 'הזמנה אישית ממותגת',
      eventLogo: 'לוגו האירוע',
      personalTitle: 'אישור הגעה אישי',
      personalInvalidTitle: 'הקישור האישי אינו תקף',
      personalInvalidBody:
        'ייתכן שהקישור פג, בוטל או הוחלף בקישור חדש. בקשו מבעלי האירוע לשלוח לכם שוב את ההזמנה האישית.',
      eventUnavailableTitle: 'האירוע אינו זמין',
      eventUnavailableBody: 'ההזמנה אינה מפורסמת כרגע. אפשר לפנות לבעלי האירוע לקבלת פרטים.',
    },
    invitation: {
      bh: 'ב״ה',
      reception: 'קבלת פנים',
      greeting: 'בברכה,',
      waze: 'ניווט ב-Waze',
      questions: 'לשאלות:',
      addToCalendar: 'הוספה ליומן',
      googleCalendar: 'Google Calendar',
      celebrationToday: 'היום חוגגים! מחכים לכם 💙',
      weekdayPrefix: 'ביום',
      countdown: {
        days: ['יום', 'יומיים', 'ימים'],
        hours: ['שעה', 'שעתיים', 'שעות'],
        minutes: ['דקה', 'דקות', 'דקות'],
        seconds: ['שנייה', 'שניות', 'שניות'],
      },
    },
    rsvp: {
      eyebrow: 'נשמח לדעת',
      title: 'אישור הגעה',
      honeypot: 'אל תמלאו שדה זה',
      fullName: 'שם מלא',
      fullNamePlaceholder: 'ישראל ישראלי',
      phone: 'טלפון',
      phoneHint: 'לעדכונים על האירוע בלבד',
      attendanceLegend: 'האם תגיעו?',
      required: '(שדה חובה)',
      attending: 'נגיע בשמחה',
      maybe: 'עדיין לא בטוח',
      notAttending: 'לא נוכל להגיע',
      countLegend: 'כמה תגיעו?',
      adults: 'מבוגרים',
      children: 'ילדים',
      babies: 'תינוקות',
      familySide: 'צד משפחה',
      notRelevant: 'לא רלוונטי',
      other: 'אחר',
      dietary: 'דרישות תזונה',
      dietaryHint: 'צמחוני, ללא גלוטן, אלרגיות — כל מה שחשוב שנדע',
      notes: 'הערות',
      consent:
        'אני מאשר/ת שהפרטים שמסרתי — כולל דרישות תזונה, שעשויות להעיד על מצב רפואי או על אורח חיים — יישמרו לצורך ארגון האירוע בלבד, ויימחקו לאחריו.',
      privacy: 'הפרטים נשמרים אצל בעלי השמחה בלבד ונמחקים לאחר האירוע.',
      limitReached: 'האירוע אינו מקבל כרגע אישורי הגעה נוספים. יש לפנות לבעלי האירוע.',
    },
    personalRsvp: {
      eyebrow: 'קישור אישי',
      hello: 'שלום',
      intro: 'אין צורך למלא שם או טלפון. בחרו תשובה אחת וזה הכול.',
      partyPrefix: 'ההזמנה משויכת ל-',
      partySuffix: ' אנשים.',
      current: 'הבחירה הנוכחית:',
      attending: 'מגיע/ה',
      attendingDescription: 'נגיע בשמחה',
      notAttending: 'לא מגיע/ה',
      notAttendingDescription: 'לא נוכל להגיע',
      maybe: 'אולי',
      maybeDescription: 'עדיין לא בטוחים',
      saving: 'שומר את הבחירה…',
      changeNote: 'אפשר לחזור לקישור ולשנות את הבחירה כל עוד הוא בתוקף.',
      chooseOne: 'יש לבחור אחת משלוש האפשרויות.',
      invalidLink: 'הקישור האישי אינו תקף עוד. בקשו מבעלי האירוע לשלוח קישור חדש.',
      eventUnavailable: 'האירוע אינו זמין כרגע.',
      saveFailed: 'שמירת האישור נכשלה. נסו שוב.',
      eventClosed: 'האירוע אינו מקבל כרגע אישורי הגעה נוספים. פנו לבעלי האירוע.',
      rateLimited: 'בוצעו יותר מדי ניסיונות. נסו שוב בעוד כמה דקות.',
      linkCannotSave: 'לא ניתן לשמור את האישור דרך הקישור הזה.',
      successAttending: 'תודה! סימנו שתגיעו בשמחה.',
      successNotAttending: 'תודה על העדכון. סימנו שלא תוכלו להגיע.',
      successMaybe: 'תודה! סימנו שעדיין אינכם בטוחים.',
    },
    dashboardNav: {
      homeAria: 'דף הבית של הלקוח',
      product: 'אישורי הגעה',
      navAria: 'ניווט באזור הלקוח',
      homeShort: 'בית',
      home: 'דף הבית שלי',
      plans: 'ניהול מסלולים',
      newEvent: 'אירוע חדש',
      signOut: 'התנתקות',
    },
    dashboard: {
      metadataTitle: 'האירועים שלי',
      eyebrow: 'לוח הבקרה',
      title: 'האירועים שלי',
      intro:
        'מכל כרטיס אפשר להיכנס לניהול מלא, לערוך את ההזמנה, לצפות בה, להעתיק את הקישור או לפתוח הודעת WhatsApp מוכנה לשליחה.',
      oneEvent: 'אירוע אחד',
      eventsSuffix: 'אירועים',
      emptyTitle: 'עדיין אין לכם אירועים',
      emptyBody: 'צרו את האירוע הראשון, עצבו אותו ובדקו עד 10 אישורי הגעה ללא תשלום.',
      emptyAction: 'יצירת האירוע הראשון',
      published: 'מפורסם',
      draft: 'טיוטה',
      when: 'מתי:',
      where: 'איפה:',
      trialTitle: 'האירוע במצב בדיקה',
      pendingTitle: 'ממתין להפעלת מסלול',
      activationBody:
        'בדיקה חינמית מוגבלת ל-10 אישורי הגעה. להפעלה מלאה בחרו Basic או Premium וצרו קשר לתשלום.',
      comparePlans: 'השוואת מסלולים',
      activateWhatsApp: 'הפעלה ב-WhatsApp',
      activationWhatsApp: 'שלום ניסן, אני רוצה להפעיל מסלול לאירוע שיצרתי במערכת אישורי הגעה.',
      license: {
        active: 'פעיל',
        trial: 'בדיקה',
        pending_payment: 'ממתין לתשלום',
        cancelled: 'בוטל',
        refunded: 'הוחזר',
        legacy: 'פעיל ללא חיוב',
      },
    },
    eventForm: {
      newMetadata: 'אירוע חדש',
      newEyebrow: 'אירוע',
      newTitle: 'אירוע חדש',
      newIntro:
        'מלאו את הפרטים ונייצר עבורכם הזמנה מעוצבת וקישור פרטי לשליחה. אפשר לשנות הכול אחר כך.',
      create: 'יצירת האירוע',
      editMetadata: 'עריכת אירוע',
      editEyebrow: 'עריכה',
      editIntro: 'שינויים מופיעים בהזמנה מיד. הקישור שכבר שלחתם נשאר אותו קישור.',
      saveChanges: 'שמירת שינויים',
      allEvents: 'כל האירועים',
      backToRsvps: 'חזרה לאישורי ההגעה',
      eventGroup: 'האירוע',
      eventType: 'סוג האירוע',
      internalTitle: 'כותרת פנימית',
      internalTitleHint: 'לזיהוי בדשבורד בלבד; האורחים לא רואים אותה.',
      internalTitlePlaceholder: 'הברית של יונתן',
      whenGroup: 'מתי',
      date: 'תאריך',
      reception: 'קבלת פנים',
      whereGroup: 'איפה',
      venue: 'שם המקום',
      venuePlaceholder: 'אולמי הדר',
      address: 'כתובת',
      addressPlaceholder: 'הרצל 12, פתח תקווה',
      wazeLink: 'קישור Waze',
      mapsLink: 'קישור Google Maps',
      httpsHint: 'חייב להתחיל ב-https://',
      invitationGroup: 'פרטים להזמנה',
      sideA: 'תווית צד א׳',
      sideB: 'תווית צד ב׳',
      emptyEquals: 'ריק =',
      contactPhone: 'טלפון לבירורים',
      contactPhoneHint: 'מוצג לאורחים בתחתית ההזמנה',
      description: 'הערה להזמנה',
      descriptionHint: 'למשל: חניה חינם במקום, או קוד לבוש',
      trackingGroup: 'מעקב',
      expectedGuests: 'כמה הזמנות שלחתם',
      expectedGuestsHint: 'לא חובה. משמש רק לחישוב אחוז המענה בדשבורד, ולא מוצג לאורחים.',
      expectedGuestsPlaceholder: 'למשל 120',
      publishingGroup: 'פרסום',
      publish:
        'פרסום ההזמנה. כשהתיבה מסומנת הקישור פתוח לאורחים; אחרת הוא מחזיר 404, ואף אחד לא יכול לאשר הגעה.',
      genericFieldsError: 'יש שדות חסרים או שגויים. הם מסומנים למעלה.',
      saving: 'שומר…',
      required: 'שדה חובה',
      chooseDate: 'יש לבחור תאריך',
      chooseType: 'יש לבחור סוג אירוע',
      actionFailed: 'הפעולה נכשלה.',
      createFailed: 'היצירה נכשלה. נסו שוב.',
      saveFailed: 'השמירה נכשלה. נסו שוב.',
      notFoundOrForbidden: 'האירוע לא נמצא, או שאין לכם הרשאה לערוך אותו.',
      expectedInvalid: 'יש להזין מספר שלם בין 1 ל-5000.',
      saved: 'נשמר.',
    },
    eventPage: {
      metadata: 'אישורי הגעה',
      allEvents: 'כל האירועים',
      editInvitation: 'עריכת ההזמנה',
      expected: 'סה״כ צפויים להגיע',
      expectedHint: 'המספר שהקייטרינג צריך',
      repliesReceived: 'תשובות שהתקבלו',
      todaySuffix: 'היום',
      attending: 'מגיעים',
      notAttending: 'לא מגיעים',
      maybe: 'מתלבטים',
      adults: 'מבוגרים',
      children: 'ילדים',
      replies: 'התשובות',
      babiesPrefix: 'כולל',
      babiesSuffix: 'תינוקות',
      countLegend: 'המספרים בסוגריים: מבוגרים / ילדים / תינוקות',
      columns: ['שם', 'טלפון', 'סטטוס', 'כמות', 'תזונה והערות', 'פעולות'],
      emptyTitle: 'עדיין לא התקבלו אישורי הגעה',
      emptyPublished: 'שלחו את הקישור שלמעלה בוואטסאפ, והתשובות יופיעו כאן ברגע שיגיעו.',
      emptyDraft:
        'ההזמנה אינה מפורסמת כרגע, כך שהקישור מחזיר 404. פרסמו אותה כדי להתחיל לאסוף תשובות.',
      publishInvitation: 'פרסום ההזמנה',
    },
    eventActions: {
      title: 'ניהול ההזמנה',
      manage: 'ניהול האירוע ואישורי ההגעה',
      guests: 'ניהול מוזמנים וייבוא מהטלפון',
      edit: 'עריכת ההזמנה',
      preview: 'צפייה בהזמנה',
      copied: 'הקישור הועתק',
      copy: 'העתקת הקישור',
      whatsapp: 'שליחת ההזמנה ב-WhatsApp',
      tools: 'כלים מתקדמים',
      copiedStatus: 'קישור ההזמנה הועתק ללוח',
      whatsappInvitePrefix: 'נשמח להזמין אתכם ל',
      whatsappDetails: 'לפרטים ולאישור הגעה:',
    },
    share: {
      title: 'הקישור להזמנה',
      intro: 'זו הכתובת ששולחים לאורחים. אפשר לשלוח עכשיו, לנהל מוזמנים או להמשיך לכלים המתקדמים.',
      whatsapp: 'שליחה בוואטסאפ',
      guests: 'ניהול מוזמנים',
      copy: 'העתקת הקישור',
      preview: 'תצוגה מקדימה',
      premium: 'מרכז Premium',
      note: 'בניהול המוזמנים אפשר להוסיף ידנית ולייבא מהטלפון. במרכז Premium נמצאים Excel, שליחה חכמה, מיתוג והושבה.',
    },
    guestsPage: {
      metadata: 'ניהול מוזמנים',
      back: 'חזרה לאירוע',
      eyebrow: 'רשימת מוזמנים',
      intro:
        'הוספה ועריכה ידנית, ייבוא אנשי קשר מהטלפון או מקובץ, שליחת קישורים אישיים ומעקב אחרי פתיחה ותשובה.',
      preview: 'צפייה בהזמנה',
      summaryAria: 'סיכום רשימת המוזמנים',
      records: 'רשומות',
      recordsHint: 'אנשי קשר פעילים',
      people: 'סה״כ אנשים',
      peopleHint: 'לפי הכמות בכל רשומה',
      opened: 'פתחו הזמנה',
      openedHint: 'קישור אישי שנפתח',
      answered: 'כבר ענו',
      answeredHint: 'מגיעים, לא מגיעים או אולי',
    },
    toolsPage: {
      metadata: 'כלים מתקדמים לאירוע',
      back: 'חזרה לאישורי ההגעה',
      proEyebrow: 'Pro · הפקה והושבה',
      premiumEyebrow: 'Premium',
      title: 'כלים מתקדמים',
      proIntro:
        'ניהול מוזמנים ושליחה אישית, מיתוג, שולחנות עם קיבולת ואזורים, הושבה חכמה, קבוצות, נגישות, דוחות, ייצוא ונקודות שחזור — מחוברים לנתוני האירוע האמיתיים.',
      premiumIntro:
        'יבוא מוזמנים מ-Excel, מרכז שליחה חכם מה-WhatsApp האישי, מעקב התקדמות, מיתוג מתקדם וניהול הושבה — מחוברים לנתוני האירוע האמיתיים במקום אחד.',
      lockedTitle: 'נדרש מסלול Premium או Pro פעיל',
      lockedBody:
        'האירוע נשאר זמין לניהול אישורי הגעה. הכלים המתקדמים נפתחים לאחר הפעלת מסלול מתאים לאירוע.',
      plans: 'צפייה במסלולים',
    },
  },
  en: {
    publicEvent: {
      brandedInvitation: 'Branded invitation',
      personalBrandedInvitation: 'Personal branded invitation',
      eventLogo: 'Event logo',
      personalTitle: 'Personal RSVP',
      personalInvalidTitle: 'This personal link is no longer valid',
      personalInvalidBody:
        'The link may have expired, been revoked or replaced. Ask the event hosts to send you a new personal invitation.',
      eventUnavailableTitle: 'This event is unavailable',
      eventUnavailableBody: 'The invitation is not currently published. Contact the event hosts for details.',
    },
    invitation: {
      bh: 'B”H',
      reception: 'Reception',
      greeting: 'Warmly,',
      waze: 'Navigate with Waze',
      questions: 'Questions:',
      addToCalendar: 'Add to calendar',
      googleCalendar: 'Google Calendar',
      celebrationToday: 'Today is the celebration! We look forward to seeing you 💙',
      weekdayPrefix: 'On',
      countdown: {
        days: ['day', 'days', 'days'],
        hours: ['hour', 'hours', 'hours'],
        minutes: ['minute', 'minutes', 'minutes'],
        seconds: ['second', 'seconds', 'seconds'],
      },
    },
    rsvp: {
      eyebrow: 'We would love to know',
      title: 'RSVP',
      honeypot: 'Leave this field empty',
      fullName: 'Full name',
      fullNamePlaceholder: 'Israel Israeli',
      phone: 'Phone number',
      phoneHint: 'Used only for event updates',
      attendanceLegend: 'Will you attend?',
      required: '(required)',
      attending: 'Yes, gladly',
      maybe: 'Not sure yet',
      notAttending: 'We cannot attend',
      countLegend: 'How many are coming?',
      adults: 'Adults',
      children: 'Children',
      babies: 'Babies',
      familySide: 'Family side',
      notRelevant: 'Not applicable',
      other: 'Other',
      dietary: 'Dietary requirements',
      dietaryHint: 'Vegetarian, gluten-free, allergies — anything the hosts should know',
      notes: 'Notes',
      consent:
        'I agree that the details I provide — including dietary requirements, which may reveal health or lifestyle information — may be stored only for organising this event and deleted afterwards.',
      privacy: 'Your details are kept only by the event hosts and deleted after the event.',
      limitReached: 'This event is not accepting additional RSVPs right now. Please contact the hosts.',
    },
    personalRsvp: {
      eyebrow: 'Personal invitation',
      hello: 'Hello',
      intro: 'No need to enter your name or phone number. Choose one answer and you are done.',
      partyPrefix: 'This invitation is for ',
      partySuffix: ' people.',
      current: 'Current answer:',
      attending: 'Attending',
      attendingDescription: 'Yes, gladly',
      notAttending: 'Not attending',
      notAttendingDescription: 'We cannot attend',
      maybe: 'Maybe',
      maybeDescription: 'Not sure yet',
      saving: 'Saving your answer…',
      changeNote: 'You can return to this link and change your answer while it remains valid.',
      chooseOne: 'Choose one of the three options.',
      invalidLink: 'This personal link is no longer valid. Ask the event hosts to send a new one.',
      eventUnavailable: 'This event is currently unavailable.',
      saveFailed: 'We could not save your RSVP. Please try again.',
      eventClosed: 'This event is not accepting additional RSVPs right now. Please contact the hosts.',
      rateLimited: 'Too many attempts were made. Please try again in a few minutes.',
      linkCannotSave: 'This RSVP cannot be saved through this link.',
      successAttending: 'Thank you! We marked you as attending.',
      successNotAttending: 'Thank you for the update. We marked you as not attending.',
      successMaybe: 'Thank you! We marked you as not sure yet.',
    },
    dashboardNav: {
      homeAria: 'Customer home',
      product: 'RSVP Manager',
      navAria: 'Customer area navigation',
      homeShort: 'Home',
      home: 'My dashboard',
      plans: 'Manage plans',
      newEvent: 'New event',
      signOut: 'Sign out',
    },
    dashboard: {
      metadataTitle: 'My events',
      eyebrow: 'Dashboard',
      title: 'My events',
      intro:
        'From each card you can manage the event, edit or preview the invitation, copy its link, or open a ready-to-send WhatsApp message.',
      oneEvent: '1 event',
      eventsSuffix: 'events',
      emptyTitle: 'You do not have any events yet',
      emptyBody: 'Create your first event, style it and test up to 10 RSVPs for free.',
      emptyAction: 'Create my first event',
      published: 'Published',
      draft: 'Draft',
      when: 'When:',
      where: 'Where:',
      trialTitle: 'This event is in trial mode',
      pendingTitle: 'Waiting for plan activation',
      activationBody:
        'The free trial is limited to 10 RSVPs. Choose Basic or Premium and contact us to activate the full event.',
      comparePlans: 'Compare plans',
      activateWhatsApp: 'Activate on WhatsApp',
      activationWhatsApp: 'Hi Nisan, I would like to activate a plan for an event I created in RSVP Manager.',
      license: {
        active: 'Active',
        trial: 'Trial',
        pending_payment: 'Payment pending',
        cancelled: 'Cancelled',
        refunded: 'Refunded',
        legacy: 'Active without billing',
      },
    },
    eventForm: {
      newMetadata: 'New event',
      newEyebrow: 'Event',
      newTitle: 'New event',
      newIntro:
        'Fill in the details and we will create a styled invitation with a private link to share. You can change everything later.',
      create: 'Create event',
      editMetadata: 'Edit event',
      editEyebrow: 'Edit',
      editIntro: 'Changes appear on the invitation immediately. The link you already shared stays the same.',
      saveChanges: 'Save changes',
      allEvents: 'All events',
      backToRsvps: 'Back to RSVPs',
      eventGroup: 'Event',
      eventType: 'Event type',
      internalTitle: 'Internal title',
      internalTitleHint: 'Used only in your dashboard; guests do not see it.',
      internalTitlePlaceholder: 'Jonathan’s celebration',
      whenGroup: 'When',
      date: 'Date',
      reception: 'Reception',
      whereGroup: 'Where',
      venue: 'Venue name',
      venuePlaceholder: 'The Garden Hall',
      address: 'Address',
      addressPlaceholder: '12 Herzl St, Petah Tikva',
      wazeLink: 'Waze link',
      mapsLink: 'Google Maps link',
      httpsHint: 'Must begin with https://',
      invitationGroup: 'Invitation details',
      sideA: 'Side A label',
      sideB: 'Side B label',
      emptyEquals: 'Blank =',
      contactPhone: 'Contact phone',
      contactPhoneHint: 'Shown to guests at the bottom of the invitation',
      description: 'Invitation note',
      descriptionHint: 'For example: free parking on site or a dress code',
      trackingGroup: 'Tracking',
      expectedGuests: 'How many invitations did you send?',
      expectedGuestsHint: 'Optional. Used only to calculate response rate and never shown to guests.',
      expectedGuestsPlaceholder: 'For example 120',
      publishingGroup: 'Publishing',
      publish:
        'Publish this invitation. When selected, the link is open to guests; otherwise it returns 404 and nobody can RSVP.',
      genericFieldsError: 'Some fields are missing or invalid. They are marked above.',
      saving: 'Saving…',
      required: 'Required field',
      chooseDate: 'Choose a date',
      chooseType: 'Choose an event type',
      actionFailed: 'The action failed.',
      createFailed: 'We could not create the event. Please try again.',
      saveFailed: 'We could not save the event. Please try again.',
      notFoundOrForbidden: 'The event was not found, or you do not have permission to edit it.',
      expectedInvalid: 'Enter a whole number between 1 and 5000.',
      saved: 'Saved.',
    },
    eventPage: {
      metadata: 'RSVPs',
      allEvents: 'All events',
      editInvitation: 'Edit invitation',
      expected: 'Expected attendees',
      expectedHint: 'The headcount your caterer needs',
      repliesReceived: 'Replies received',
      todaySuffix: 'today',
      attending: 'Attending',
      notAttending: 'Not attending',
      maybe: 'Maybe',
      adults: 'Adults',
      children: 'Children',
      replies: 'Replies',
      babiesPrefix: 'Includes',
      babiesSuffix: 'babies',
      countLegend: 'Numbers in parentheses: adults / children / babies',
      columns: ['Name', 'Phone', 'Status', 'Count', 'Dietary & notes', 'Actions'],
      emptyTitle: 'No RSVPs yet',
      emptyPublished: 'Share the invitation link above on WhatsApp and replies will appear here as they arrive.',
      emptyDraft: 'The invitation is not published, so its link currently returns 404. Publish it to start collecting replies.',
      publishInvitation: 'Publish invitation',
    },
    eventActions: {
      title: 'Invitation management',
      manage: 'Manage event and RSVPs',
      guests: 'Manage guests and import contacts',
      edit: 'Edit invitation',
      preview: 'Preview invitation',
      copied: 'Link copied',
      copy: 'Copy link',
      whatsapp: 'Send invitation on WhatsApp',
      tools: 'Advanced tools',
      copiedStatus: 'Invitation link copied to clipboard',
      whatsappInvitePrefix: 'We would love to invite you to ',
      whatsappDetails: 'Details and RSVP:',
    },
    share: {
      title: 'Invitation link',
      intro: 'This is the address to send to guests. Share it now, manage guests, or continue to the advanced tools.',
      whatsapp: 'Send on WhatsApp',
      guests: 'Manage guests',
      copy: 'Copy link',
      preview: 'Preview',
      premium: 'Premium centre',
      note: 'Guest management supports manual entry and phone import. Premium includes Excel, smart sending, branding and seating.',
    },
    guestsPage: {
      metadata: 'Guest management',
      back: 'Back to event',
      eyebrow: 'Guest list',
      intro:
        'Add and edit guests manually, import contacts from your phone or a file, send personal links, and track opens and replies.',
      preview: 'Preview invitation',
      summaryAria: 'Guest list summary',
      records: 'Records',
      recordsHint: 'Active contacts',
      people: 'Total people',
      peopleHint: 'Based on party size per record',
      opened: 'Opened invitation',
      openedHint: 'Personal link was opened',
      answered: 'Already replied',
      answeredHint: 'Attending, not attending or maybe',
    },
    toolsPage: {
      metadata: 'Advanced event tools',
      back: 'Back to RSVPs',
      proEyebrow: 'Pro · production & seating',
      premiumEyebrow: 'Premium',
      title: 'Advanced tools',
      proIntro:
        'Guest management and personal sending, branding, capacity-aware tables and zones, smart seating, groups, accessibility, reports, exports and restore points — all connected to the event’s live data.',
      premiumIntro:
        'Import guests from Excel, smart sending from your personal WhatsApp, progress tracking, advanced branding and seating — connected to the event’s live data in one place.',
      lockedTitle: 'An active Premium or Pro plan is required',
      lockedBody: 'RSVP management remains available. Advanced tools unlock after an eligible plan is activated for this event.',
      plans: 'View plans',
    },
  },
} as const;

export function getAppCopy(locale: Locale) {
  return APP_COPY[locale];
}
