import { spawnSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import { config as loadDotenv } from 'dotenv';

/**
 * Regenerates `types/database.types.ts` from the live schema (§2, §10.1).
 *
 * The generated file is the single source of truth for row shapes; nothing in
 * `repositories/` may hand-write a table type. It is also the one file excluded
 * from the 100% coverage requirement, which is only defensible while it stays
 * genuinely generated — so this script overwrites it wholesale and never patches it.
 *
 * Connection: the Supabase CLI can read the schema either from a project ref (which
 * needs a personal access token) or straight from a connection string. The
 * connection string is preferred here because it is the same value the integration
 * and RLS suites already require, so there is one credential to configure, not two.
 */

loadDotenv({ path: '.env.local', quiet: true });

const OUTPUT_PATH = resolve('types/database.types.ts');

function buildCliArgs(): string[] {
  const databaseUrl = process.env.TEST_DATABASE_URL;
  if (databaseUrl) {
    return ['supabase', 'gen', 'types', 'typescript', '--db-url', databaseUrl];
  }

  const projectRef = process.env.SUPABASE_PROJECT_REF;
  if (projectRef && process.env.SUPABASE_ACCESS_TOKEN) {
    return ['supabase', 'gen', 'types', 'typescript', '--project-id', projectRef];
  }

  throw new Error(
    'Nothing to connect to. Set TEST_DATABASE_URL in .env.local (preferred), or set ' +
      'both SUPABASE_PROJECT_REF and SUPABASE_ACCESS_TOKEN. See SETUP.md.',
  );
}

function main(): void {
  const args = buildCliArgs();

  const result = spawnSync('npx', ['--yes', ...args], {
    encoding: 'utf8',
    shell: process.platform === 'win32',
  });

  if (result.error) throw result.error;
  if (result.status !== 0) {
    // stderr carries the CLI's own diagnostics; reprint them rather than guessing.
    throw new Error(`supabase gen types exited with ${result.status}\n${result.stderr}`);
  }

  const generated = result.stdout;
  // A silent truncation here would leave a file that still type-checks but describes
  // a schema that no longer exists, which is worse than a hard failure.
  if (!generated.includes('export type Database')) {
    throw new Error('The CLI produced output that does not look like generated types.');
  }

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(
    OUTPUT_PATH,
    `// Generated by \`pnpm supabase:types\`. Do not edit by hand.\n${generated}`,
    'utf8',
  );

  console.warn(`✓ wrote ${OUTPUT_PATH} (${generated.split('\n').length} lines)`);
}

try {
  main();
} catch (error) {
  console.error('✗ type generation failed:', error instanceof Error ? error.message : error);
  process.exitCode = 1;
}
