-- Multi-tenancy: an event belongs to the account that created it (§4.1, §4.4).
--
-- Until now the schema modelled one deployment, one celebration:
-- `events_single_active_idx` was a unique index on the constant `true`, so at most
-- one row could ever have `is_active`. That is a template, not a service. Publishing
-- a second event required un-publishing the first.
--
-- The change that matters is not the extra columns — it is that authorisation stops
-- being global. `is_admin()` answers "is this person staff", which in a
-- single-tenant system was the same question as "may this person see this event". It
-- is not the same question any more, and continuing to ask it would let any account
-- read every other account's guest list. Ownership is now per row, and every policy
-- is rewritten against it.

alter table public.events
  add column owner_user_id uuid references auth.users (id) on delete cascade,
  -- Unguessable, not sequential and not derived from the title (§4.2 forbids
  -- sequential public identifiers). Generated by the application from a CSPRNG so
  -- that guessing one URL never reveals that others exist.
  add column public_id text;

-- Backfilled below for the row that predates this migration, then made mandatory.
update public.events set public_id = encode(gen_random_bytes(9), 'base64')
  where public_id is null;
update public.events
   set public_id = replace(replace(replace(public_id, '+', '-'), '/', '_'), '=', '')
 where public_id is not null;

alter table public.events
  alter column public_id set not null,
  add constraint events_public_id_unique unique (public_id),
  add constraint events_public_id_shape check (public_id ~ '^[A-Za-z0-9_-]{10,32}$');

create index events_owner_idx on public.events (owner_user_id);

-- The whole point of the migration: many events may be live at once, each its own.
drop index if exists public.events_single_active_idx;

comment on column public.events.public_id is
  'Unguessable public URL segment. The invitation lives at /e/{public_id} (§4.2).';
comment on column public.events.owner_user_id is
  'The account that owns this event. Every RLS policy in the schema keys off it.';

/**
 * Does the caller own this event?
 *
 * SECURITY DEFINER so it can read `events` while the caller cannot, and
 * `search_path = ''` so a caller-controlled search_path cannot redirect any object
 * it names — hence the fully qualified references.
 *
 * Verified earlier in this build: RLS policy evaluation *does* require the caller to
 * hold EXECUTE on a function a policy calls. Revoking it from `authenticated` makes
 * every policy fail with "permission denied for function". The grant below is
 * therefore load-bearing, not tidiness.
 */
create or replace function public.owns_event(p_event_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
      from public.events e
     where e.id = p_event_id
       and e.owner_user_id = (select auth.uid())
  );
$$;

comment on function public.owns_event(uuid) is
  'True when the current user owns the given event. The basis of tenant isolation.';

revoke all on function public.owns_event(uuid) from public, anon;
grant execute on function public.owns_event(uuid) to authenticated;

-- ── Policies, rewritten from "is staff" to "owns this row" ───────────────────────

drop policy if exists events_admin_manage on public.events;
drop policy if exists guests_admin_manage on public.guests;
drop policy if exists rsvps_admin_manage on public.rsvps;
drop policy if exists audit_logs_admin_read on public.audit_logs;

create policy events_owner_manage on public.events
  for all to authenticated
  using (owner_user_id = (select auth.uid()))
  -- WITH CHECK as well as USING: without it an owner could update a row to hand it
  -- to somebody else, or insert a row already owned by another account.
  with check (owner_user_id = (select auth.uid()));

create policy guests_owner_manage on public.guests
  for all to authenticated
  using (public.owns_event(event_id))
  with check (public.owns_event(event_id));

create policy rsvps_owner_manage on public.rsvps
  for all to authenticated
  using (public.owns_event(event_id))
  with check (public.owns_event(event_id));

-- Audit history stays read-only to every client role (§4.7). Scoped by the event it
-- refers to; rows with no event_id in metadata are platform-level and stay hidden.
create policy audit_logs_owner_read on public.audit_logs
  for select to authenticated
  using (
    metadata ? 'event_id'
    and public.owns_event((metadata ->> 'event_id')::uuid)
  );

-- invite_sessions and idempotency_keys keep no policies and no grants at all:
-- only server-side privileged code touches them (§4.1).
